# SCREEN:
SCREEN_HEIGHT = 64
SCREEN_WIDTH  = 64
SCREEN_HEIGHT_HALF = SCREEN_HEIGHT // 2
SCREEN_WIDTH_HALF  = SCREEN_WIDTH  // 2
SCREEN_HEIGHTXWIDTH = SCREEN_HEIGHT * SCREEN_WIDTH

# PIXELS:
OCCUPIED_PIXEL = "▀"

# ANSI:
RESET = "\033[0m"

# UPDATE:
DELTA_TIME = 1
FPS = 1 / DELTA_TIME
TIME = 0
QUIT = False
